### ISSUE TITLE
謝謝你的心得

### ISSUE THREAD

**Issue by azole** [kiyo415411/git-workshop#1]
謝謝你的心得，你的文筆還不錯呢，讀起來很流暢舒適。筆記也整理得很好，鼓勵你們持續在課後做筆記，屬於自己的，之後面試前需要複習的話，這些材料會是最棒的資源！

提醒一下，是 readme，不是 reademe.md，多了一個 e，你可以調整看看，然後觀察看看 github 會怎麼處理這個檔案、有什麼效果？如果有嘗試的話，務必將調整後的結果分享給我，好嗎？

之後的課程進行方式，如果有任何問題，請隨時讓我知道，讓我們可以更好地一起學習！

**Comment by kiyo415411** [comment]
謝謝老師的回覆！關於我調整後的結果為下。

首先是在 vscode 更正為 readme.md 之後，圖示發生變化。

![image](https://user-images.githubusercontent.com/60590270/167257907-da4e6477-cbce-483b-acf7-d97f9af3a87f.png)

回到 github 查看後，發現 readme.md 有將標題列為目錄的效果，可以直接選擇想看的部分。

![image](https://user-images.githubusercontent.com/60590270/167257701-690cce62-6d46-48d6-8b70-de7691bdea80.png)

並且在 repo 的檔案列表，就能看到 readme.md 的內容，完全就是使用說明的概念，非常方便有趣！
![image](https://user-images.githubusercontent.com/60590270/167257821-4fb76116-aaad-4f29-9bdf-66c78ee825d4.png)
